package com.jdbc.day3;

import org.junit.Test;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

public class JDBCPractice {
    final String DB_URL = "jdbc:oracle:thin:@54.152.21.73:1521:xe";
    final String DB_USER = "hr";
    final String DB_PASSWORD = "hr";

    @Test
    public void connectToDB() throws Exception{
        /**
         * To connect with a database we call DriverManager
         * Provide DB connection URL. username and password
         * By default, JDBC does auto commit
         */
        Connection connection = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD);
//        connection.setAutoCommit(false); to disable auto commit
//        if don't commit, we can call rollback function to revert changes
//        if auto commit is disabled, at the end we have to call connection.commit() method to make changes permanent
//        only DML commands can ge reverted: INSERT, UPDATE, DELETE
        /**
         * statement is used to execute a query
         */
        Statement statement = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        /**
         * A table of data representing a database result set,
         * which is usually generated by executing a statement that queries the database
         * It pointer will be before first row, we need to call next() method
         * To switch pointer and move it to the first row
         */
        ResultSet resultSet = statement.executeQuery("SELECT * FROM employees");
        resultSet.next(); //returns boolean, and moves pointer to the next row in result set if it present
        String firstName = resultSet.getString("first_name");
        String lastName = resultSet.getString("last_name");
        /**
         * either (1) the row count for SQL Data Manipulation Language (DML) statements
         *     or (2) 0 for SQL statements that return nothing
         */
//        statement.executeUpdate("UPDATE employees SET first_name = 'Steven', last_name='King' WHERE employee_id = 100");
        System.out.println(firstName);
        System.out.println(lastName);
        resultSet.close();
        statement.close();
        connection.close();
    }
}
